name: pypsa
channels:
- conda-forge
dependencies:
- python>=3.9
- numpy
- scipy
- pandas>=0.24.0
- xarray
- netcdf4
- libnetcdf
- pytables
- matplotlib
- networkx>=2
- cartopy>=0.16
- geopandas>=0.9
- glpk
- linopy>=0.2
- deprecation
- validators
#  - coincbc
#  - gurobi::gurobi
- pip
- pip:
  - pyomo>=5.7,<6.6.2; python_version < '3.12'
