name: pypsa
channels:
  - conda-forge
dependencies:
  - python
  - six >= 1.13.0
  - numpy
  - pyomo
  - scipy
  - pandas>=0.24.0
  - pytables
  - matplotlib
  - networkx>=1.10
  - pyomo
  - cartopy>=0.16
#  - coincbc
  - glpk
  - gurobi::gurobi
