name: pypsa
channels:
- conda-forge
dependencies:
- python>=3.9
- numpy
- scipy
- pandas>=0.24.0
- xarray
- netcdf4
- libnetcdf
- pytables
- matplotlib
- networkx>=2
- cartopy>=0.16
- geopandas>=0.9
- linopy>=0.3.9
- deprecation
- validators
- pip
- pip:
  - highspy
