name: pypsa
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - pyomo
  - scipy
  - pandas>=0.24.0
  - pytables
  - matplotlib
  - networkx>=1.10
  - pyomo>=5.7.0
  - cartopy>=0.16
  - glpk
  - deprecation
#  - coincbc
#  - gurobi::gurobi
