name: CI with conda

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        python-version:
        - 3.8
        os:
        - ubuntu-latest
        # - macos-latest
        # - windows-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}
    # - name: Add conda to system path
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     echo $CONDA/bin >> $GITHUB_PATH
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
    - name: Add cbc to environment if not windows
      if: matrix.os != 'windows-latest'
      run: |
        echo "  - coincbc" >> environment.yaml
    - name: Install dependencies  
      shell: bash -l {0}
      run: |
        conda config --add pinned_packages python=${{ matrix.python-version }}
        mamba env update --file environment.yaml --name test
        mamba env update --file environment_dev.yaml --name test
        pip install --no-cache-dir --no-deps -e .
    - name: List installed packages
      shell: bash -l {0}
      run: |
        conda env list
        conda list
    # conda activate pypsa
    # - name: Lint with flake8
    #   run: |
    #     mamba install -c conda-forge flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
